### ISSUE TITLE
Move over most recent changes from MS3 repository

### ISSUE THREAD

**Issue by fugu13** [datasonnet/datasonnet-mapper#59]
This will probably require a manual merge due to rebasing in the main branch there

**Comment by jam01** [comment]
- [ ] support for grouped documents input
- [ ] re-enables namespace override xml read test
- [ ] re-enable mappertest
- [ ] import repository issues

Header issues:
- [ ] unrecognized line should not throw an exception, forwards compatibility
- [ ] unrecognized version should not throw an exception, forwards compatibility
- [ ] the value of default outputs is still not clear

**Comment by fugu13** [comment]
We won't need to re-enable the namespace override test, that's been re-enabled in this repo since I added namespace support. All the others in the first section look fine (though of course, importing issues from your repository is a meta issue). I propose we de prioritize the github pages bit (though it shouldn't be hard) as it doesn't affect the exported functionality. Will someone on your team be doing them or should I undertake to do so?

I am strongly against unrecognized lines not throwing an exception. An unrecognized header line being ignored virtually guarantees behavior will not be what's expected. Furthermore, if unrecognized header lines are accepted, and then the underlying datasonnet engine is updated to include support for that line, then the behavior of existing scripts that have not changed at all will  suddenly change due to the header line now being recognized, which is a very bad thing. Also, if have a typo in a header line (at least the first part), you won't be told there's an issue, you'll just have mysterious missing behavior.

I am slightly less strongly against unrecognized versions not throwing an exception, since (if every header line is understood), then there's a decent possibility all the code in the script is acceptable, and it could be tested and run. I am still against it, because some issues might not be apparent on brief testing (such as code paths that use nonexistent functions, but don't come up in a quick check that the script still works), and also because one of the points of the version is to be a strong signal on runtime compatibility.

Re: default outputs, the reason "default" was added to the output is to resolve the question of "what gets done if any/any is provided as the output", which needs to be one of the configured outputs. As for why there are multiple outputs, that's a pretty definite requirement for us. Some scenarios that have come up for us are to want to configure some options for eg both Java and JSON, or Java and CSV. If we want to remove the "accepts any/any for output type" possibility I'm fine with getting rid of the default output functionality

**Comment by fugu13** [comment]
Btw, I don't see anything in the above around the XML functionality, did we still want to talk through some of that?

**Comment by jam01** [comment]
Thanks for the reply :)

On the namespace test, I guess we missed it when we cherry picked that piece. It's checkmarked now.

On the github pages CI, this is definitely not as high priority as others, but still a must. We have developers making use of the docs and the ci is the only way to guarantee they're looking at the right info.

On the header exceptions, ultimately graceful degradation is better than simply not working. This W3C document is where I'm coming from [Forwards Compatibility: Must Accept Unknowns](https://www.w3.org/2001/tag/doc/versioning-compatibility-strategies#iddiv290818088). It's kinda standard.

On default output, I've changed my mind and see the multiple outputs support does have value. Could we instead of introducing another keywork `default output` just take whichever is last? It'd leave the standard use case simple, plus prevents the complexity on the Header API. I'm thinking we could encapsulate the defaulting logic within the Header and preserve the previous signatures.

On XML mixed content, I think the new format deviates from the badgerfish convention, at least as I understand it. For example, in this [online converter](http://dropbox.ashlock.us/open311/json-xml/) if you put the input for the mixed content test, you'll get back what we had before, which is what I would expect after reading the badgerfish convention docs. Plus I think as it was before it should still preserve order in a round trip, no? Since the writer iterates on the elements in the right order, regardless of the type... I think.

Some of this stuff is probably easier to discuss verbally, so if you want to jump on a call let me know.

**Comment by fugu13** [comment]
I'll post a few things here to document some thoughts, but would be glad to hop on a call.

Forward compatibility is only standard in certain contexts. For HTML, the reason it is forward compatible is because doing something when displaying visuals is better than doing nothing, especially with a plethora of clients and some folks being stuck on old code. When transforming data for a financial transaction, that's not the case. Numerous major standards are not forward compatible. Two that spring to mind are, Apache Arrow specifically calls out that if an older client library finds file structure it can't handle it will fail completely (because silently reading wrong data is very bad), SQLite has had several non-forwards-compatible file format changes (deliberately, because integrity of the database would fail if they didn't), and I can provide others as needed.

It's useful to note the caveat at the beginning of what you link: "A language whose syntax allows additional unknown text"--this isn't a general rule to follow, it is opting into a practice in a specific context.

Imagine folks out there running Camel, and they move a script over to another Camel deployment, and it works... except for some reason no matter what they change the output is never XML like the docs say it should be, it is always JSON. They double check the headers, they triple check the headers, everything is perfect, yet it doesn't work? Well, maybe we changed something about how outputs are specified (as just happened across these versions), and their perfect lines, that perfectly match the newest version of DataSonnet's docs, don't match the older version of DataSonnet that the second Camel uses, but the older version is just silently ignoring the headers it doesn't recognize. Heck, even if for some reason some of their functions don't work, imagine how mystified they'll be. The functions are documented, and they've got the right version header, why aren't those functions working?

The story is much better if we are strict about the headers. They get a message saying that the version of DataSonnet they're using doesn't support 3.0, only 1.0 and 2.0,  and they should either upgrade or attempt to modify the script for use with 2.0. If they choose the latter and change the script header to 2.0, then they're told which header lines don't work, and can fix them.

**Comment by fugu13** [comment]
Re: default as a keyword, I like explicit better. Someone only occasionally reading or writing the headers can't be expected to have memorized a behavior like "last as default". The most common use case is a single output configuration, and that will still be treated as the default. There won't be anything wrong with specifying multiple without a default, either, there just won't be a default if used in an any/any situation, so all existing headers using the new format will continue working.

**Comment by fugu13** [comment]
For XML, a few things.

First, with the previous setup, tags that are the same will end up in the same array, so even if ordering is relied on, it won't be possible to reconstitute the mixed content.

Second, probably the most common use case I'm aware of for mixed content in data transformation would be working with the mixed content exactly and completely. For example, someone might well have XML something like:

```xml
<comments>
  <comment>
    You can go to <a href="">here</a> to find out more about platypuses specifically, or <a href="">over here</a> to find out more about monotremes in general.
  </comment>
</comments>
```

Someone when transforming that is generally going to want to bring along the whole mixed content and put it in some other place in the output structure. That isn't possible with the previous output.

Third, even if relying on ordering did allow round tripping, JSON objects aren't ordered (to quote from json.org, "An object is an unordered set of name/value pairs."). If someone used another tool to generate sections of JSON they expect DataSonnet to turn into XML, we can't rely on any particular ordering.

**Comment by fugu13** [comment]
Btw, something I realized I might not have made clear with the version header in the DataSonnet files: it isn't intended to tick anywhere near as rapidly as the DataSonnet main version. I could see it being several major versions of the java code before the header changes even one major version.

Additionally, I'd be very open to modifying the code so not-specifically-understood minor versions are still allowed to run (with a warning logged of course), and reserving header version rejection only for major version changes.

**Comment by jam01** [comment]
Hey Russell.

So on the header, you make good points about compatibility. Though I still prefer to leave the debugging to developers if something doesn't work, I think compromising on allowing forward minor versions is fair. I'll strike those through once we make those changes.

I think the `default output` and xml changes are more significant, because they are big changes in functionality and API, that I'm not sure we should be doing at this moment as we're trying to ship in Camel 3.7. On XML, we're basically discussing an entirely different format than badgerfish in order to enable round tripping, which is valuable, but it's a breaking change. And for the header I think the implicit behavior of 'last output' is a fine tradeoff for keeping the Header API simple. After all the use case of multiple outputs is a very minimal fraction.

**Comment by jam01** [comment]
Or we could rely on the quality factor media type parameter to signal which is preferred. I think that'd achieve both the functionality and leave the Header API as it is.

**Comment by fugu13** [comment]
I think the quality idea for default might be a good solution, I'll review the RFCs to make sure I'm understanding it fully

**Comment by fugu13** [comment]
Re: the badgerfish convention, we're already diverging from the original badgerfish convention (which didn't have indexed text at all), and the example implementation of the one variant we're looking at has various bugs and oddities (for example, it does strange things when xml tags are single characters). Several of the other implementations seem to be minor variants as well.

I think getting to a badgerfish implementation that supports round tripping XML--which is the same as complete support for XML semantics--is a good idea even if it ends up being a slight updating of one variant of the convention. We have to document our implementation fully, either way, the quick description on the converter page isn't enough.

**Comment by jam01** [comment]
so apparently there's no way to migrate issues across orgs so will need to replicate the issues

**Comment by fugu13** [comment]
All merged!
